image: debian:stable

variables:
  DEPENDENCIES: docbook-xml docbook-xsl pkgconf systemd-dev xsltproc meson
  LANG: C.UTF-8

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_PIPELINE_SOURCE == 'push'

stages:
  - build

build:
  before_script:
    - apt-get update -qq && apt-get install -yq eatmydata
    - eatmydata apt-get install -yq $DEPENDENCIES

  script:
    - meson setup build
    - meson compile -C build
    - DESTDIR=/tmp/test-install meson install -C build
